forge 'https://forge.puppet.com'

# MySQL
mod 'puppetlabs/mysql',  '10.10.0'
mod 'puppetlabs/stdlib', '8.1.0'

# Redis
mod 'puppet/redis',       '8.2.0'
mod 'puppet/systemd',     '3.5.1'
mod 'puppetlabs/inifile', '5.2.0'